### ISSUE TITLE
BasetexturerenderTest failes on Linux

### ISSUE THREAD

**Issue by kimkulling** [kimkulling/osre#53]
How to reproduce:
--------------------
 - Build rendertest for linux
 - Run the rendertest
 - The baseTextureRenderTest failes.

The following callstack was performed:

```
Info: <= Destroying test. (test/RenderTests/src/AbstractRenderTest.cpp, 65)( rendertest/basetexturerendertest ) ( 01.20.2020 19:39:06  ) 
Dbg:  BaseTextureRenderTest::onDestroy (test/RenderTests/src/BaseTextureRenderTest.cpp, 147)( BasetexturerenderTest ) ( 01.20.2020 19:39:06  ) 
Info: => Creating test. (test/RenderTests/src/AbstractRenderTest.cpp, 52)( rendertest/DbgFontRenderTest ) ( 01.20.2020 19:39:06  ) 
  Dbg:  Cannot find attribute normal in shader. (src/Engine/RenderBackend/OGLRenderer/OGLShader.cpp, 160)( OGLShader ) ( 01.20.2020 19:39:06  ) 
  Dbg:  Cannot find attribute color0 in shader. (src/Engine/RenderBackend/OGLRenderer/OGLShader.cpp, 160)( OGLShader ) ( 01.20.2020 19:39:06  ) 
  Dbg:  Cannot find normal (src/Engine/RenderBackend/OGLRenderer/OGLRenderBackend.cpp, 457)( OGLRenderBackend ) ( 01.20.2020 19:39:06  ) 
  Dbg:  Cannot find color0 (src/Engine/RenderBackend/OGLRenderer/OGLRenderBackend.cpp, 457)( OGLRenderBackend ) ( 01.20.2020 19:39:06  ) 

Thread 1 "osre_rendertest" received signal SIGSEGV, Segmentation fault.
0x00007ffff748bc13 in OSRE::RenderBackend::RenderBackendService::commitNextFrame() () from /home/kimmi/10_projects/osre/lib/libosre.so
(gdb) bt
#0  0x00007ffff748bc13 in OSRE::RenderBackend::RenderBackendService::commitNextFrame() () from /home/kimmi/10_projects/osre/lib/libosre.so
#1  0x00007ffff748bcd0 in OSRE::RenderBackend::RenderBackendService::onUpdate() [clone .localalias.47] () from /home/kimmi/10_projects/osre/lib/libosre.so
#2  0x0000555555569297 in OSRE::RenderTest::RenderTestSuite::update() ()
#3  0x0000555555564dd0 in main ()
(gdb) quit
A debugging session is active.
 
```

How to fix:
------------
ToDo

**Comment by kimkulling** [comment]
Fixed
